# Spring Configuration
spring:
  application:
    name: "desmos-blockchain-connector"
  main:
    web-application-type: reactive
  r2dbc:
    url: "r2dbc:postgresql://localhost:5433/desmos"
    username: "guest"
    password: "guest"
    generate-unique-name: true
  flyway:
    url: "jdbc:postgresql://localhost:5433/desmos"
    locations: classpath:db/migrations

# Spring Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.desmos: INFO

# Spring Management Configuration - Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# SpringDoc Configuration - OpenAPI 3.0 Documentation & Swagger UI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Server Configuration
server:
  port: 8080

# Application Configuration
openapi:
  server:
    url: "https://localhost:9091"
    description: "Blockchain Connector Test Server"
  info:
    title: "Blockchain Connector"
    version: "2.0.0-SNAPSHOT"
    description: "Blockchain Connector Component"
    termsOfService: "https://example.com/terms-of-service"
    license:
      name: "Apache 2.0"
      url: "https://www.apache.org/licenses/LICENSE-2.0.html"
    contact:
      email: "info@example.com"
      name: "john doe"
      url: "https://example.com"

# Operator Configuration
client:
  organizationId: "VATES-99999999"

# Context Broker Configuration
broker:
  provider: "scorpio"
  externalDomain: "http://localhost:9090"
  internalDomain: "http://localhost:9090"
  paths:
    entities: "/ngsi-ld/v1/entities"
    subscriptions: "/ngsi-ld/v1/subscriptions"
    temporal: "/ngsi-ld/v1/temporal/entities"

# NGSI Subscription Configuration
ngsi-subscription:
  notificationEndpoint: "http://localhost:8080/notifications/broker"
  entityTypes: "ProductOffering,ProductOrder"

# DLT Adapter Configuration
dlt-adapter:
  provider: "digitelts"
  internalDomain: "http://localhost:8080"
  externalDomain: "http://localhost:8080"
  paths:
    publication: "/api/v1/publishEvent"
    subscription: "/api/v1/subscribe"
    events: "/api/v1/events"

# Event Subscription Configuration
event-subscription:
  notificationEndpoint: "http://localhost:8080/notifications/evm"
  eventTypes: "ProductOffering,ProductOrder"

#ELK Configuration
elasticsearch:
  username: elastic
  password: "elastic"

kibana:
  username: kibana_system
  password: "kibana"

stack_version: 8.12.2

cluster_name: "ELK cluster"

es_port: 9200
kibana_port: 5601
logstash_port: 5044

es_mem_limit: 4294967296
kb_mem_limit: 1073741824
ls_mem_limit: 1073741824